// Mocks generated by Mockito 5.4.4 from annotations
// in kiota_abstractions/test/authentication/base_bearer_token_authentication_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kiota_abstractions/kiota_abstractions.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAllowedHostsValidator_0 extends _i1.SmartFake
    implements _i2.AllowedHostsValidator {
  _FakeAllowedHostsValidator_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccessTokenProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessTokenProvider extends _i1.Mock
    implements _i2.AccessTokenProvider {
  MockAccessTokenProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AllowedHostsValidator get allowedHostsValidator => (super.noSuchMethod(
        Invocation.getter(#allowedHostsValidator),
        returnValue: _FakeAllowedHostsValidator_0(
          this,
          Invocation.getter(#allowedHostsValidator),
        ),
      ) as _i2.AllowedHostsValidator);

  @override
  _i3.Future<String> getAuthorizationToken(
    Uri? uri, [
    Map<String, Object>? additionalAuthenticationContext,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuthorizationToken,
          [
            uri,
            additionalAuthenticationContext,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getAuthorizationToken,
            [
              uri,
              additionalAuthenticationContext,
            ],
          ),
        )),
      ) as _i3.Future<String>);
}
